"use client";
import{useEffect,useState}from"react";import{getAnalysis,reportUrl}from"../../../lib/api";
const val=x=>typeof x==="string"?x:(x?.title||x?.finding||x?.statement||x?.action||JSON.stringify(x));
function Section({title,items}){if(!items?.length)return null;return <section className="report-section"><div className="eyebrow">{title}</div>{items.map((x,i)=><div className="report-item" key={i}><span>{String(i+1).padStart(2,"0")}</span><div>{val(x)}</div></div>)}</section>}
export default function Report({params}){const[a,setA]=useState(null),[error,setError]=useState("");
 useEffect(()=>{getAnalysis(params.id).then(setA).catch(e=>setError(e.message))},[params.id]);
 if(error)return <main className="shell"><p>{error}</p></main>; if(!a)return <main className="shell"><p className="muted">Loading report…</p></main>;
 const r=a.result||{};return <main className="report-shell"><header className="report-top"><a className="brand" href="/">Friction</a><div className="report-actions"><a href="/history">History</a><a href={"/analysis/"+a.id}>Analysis</a><a className="cta small" href={reportUrl(a.id)} target="_blank" rel="noreferrer">Open report</a></div></header>
 <section className="report-hero"><div><div className="eyebrow">Full diagnostic report</div><h1>{a.input?.business?.name||"Business"}</h1><p className="lede">Evidence-led onboarding diagnosis · {r.diagnosis_status||"insufficient_evidence"}</p></div><div className="confidence-card"><div className="eyebrow">Confidence</div><strong>{r.confidence?.score??"—"}/100</strong><div className="muted">{r.confidence?.band||"—"}</div></div></section>
 <section className="report-grid"><div className="card"><div className="eyebrow">Executive diagnosis</div><p>{r.summary||r.findings?.[0]?.statement||r.findings?.[0]?.title||"The available evidence does not establish a stronger conclusion yet."}</p><div className="muted">Review the evidence before making a redesign decision.</div></div><div className="card"><div className="eyebrow">Evidence model</div><div className="stack"><span>Observed facts · {r.facts?.length||0}</span><span>Hypotheses · {r.hypotheses?.length||0}</span><span>Uncertainties · {r.uncertainties?.length||0}</span><span>Next evidence · {r.next_evidence?.length||0}</span></div></div></section>
 <Section title="What we observed" items={r.facts}/><Section title="What it could mean" items={r.hypotheses}/><Section title="Key findings" items={r.findings}/><Section title="Recommendations" items={r.recommendations}/><Section title="What would confirm it" items={r.next_evidence}/><Section title="Uncertainties" items={r.uncertainties}/><Section title="Data quality" items={r.data_quality}/>
 <footer className="report-footer"><div><strong>Friction</strong><div className="muted">Find friction. Fix onboarding.</div></div><a href="https://www.linkedin.com/" target="_blank" rel="noreferrer">Founder DM ↗</a></footer>
 </main>}