"use client";
import{useEffect,useState}from"react";import{getAnalysis,runAnalysis,reportUrl}from"../../../lib/api";
const val=x=>typeof x==="string"?x:(x?.title||x?.finding||x?.statement||x?.action||JSON.stringify(x));
function Block({title,items}){if(!items?.length)return null;return <section className="section"><div className="eyebrow">{title}</div>{items.map((x,i)=><div className="item" key={i}><span>{String(i+1).padStart(2,"0")}</span><div>{val(x)}</div></div>)}</section>}
export default function Analysis({params}){const[a,setA]=useState(null),[err,setErr]=useState(""),[busy,setBusy]=useState(false);useEffect(()=>{getAnalysis(params.id).then(setA).catch(e=>setErr(e.message))},[params.id]);
 async function run(){setBusy(true);try{setA(await runAnalysis(a.id))}catch(e){setErr(e.message)}finally{setBusy(false)}}
 if(err)return <main className="shell"><div className="card error">{err}</div></main>;if(!a)return <main className="shell"><p className="muted">Loading…</p></main>;const r=a.result||{};
 return <main className="shell"><nav className="nav"><div className="brand">Friction</div><div><a href="/history">History</a></div></nav>
 <div className="eyebrow">Analysis</div><h1>Evidence before opinion.</h1><p className="lede">{a.input?.business?.name||"Business"} · {a.input?.onboarding?.activation||"Activation definition missing"}</p>
 {a.status!=="completed"?<div className="card"><p>Ready to test the available evidence.</p><button className="cta" onClick={run} disabled={busy}>{busy?"Building diagnosis…":"Run diagnosis"}</button></div>:
 <><section className="card result-head"><div><div className="eyebrow">Diagnosis status</div><h2>{r.diagnosis_status}</h2><p className="muted">Confidence {r.confidence?.score??"—"}/100 · {r.confidence?.band||"—"}</p></div><a className="cta" href={"/report/"+a.id}>View full report</a></section>
 <div className="diagnosis-layout"><div><Block title="What we observed" items={r.facts}/><Block title="What it could mean" items={r.hypotheses}/><Block title="Key findings" items={r.findings}/><Block title="Recommendations" items={r.recommendations}/><Block title="What would confirm it" items={r.next_evidence}/></div><aside className="card"><div className="eyebrow">Confidence breakdown</div><strong>{r.confidence?.score??"—"}/100</strong><p className="muted">Evidence {Math.round((r.confidence?.factors?.evidenceCompleteness||0)*100)}% · context {Math.round((r.confidence?.factors?.contextClarity||0)*100)}%</p></aside></div></>}
 </main>}