const{validateAnalysisInput}=require('./validator');const{analyzeFunnel}=require('./funnel');const{buildHypotheses}=require('./hypotheses');const{scoreConfidence}=require('./confidence');const{validateDiagnosis}=require('./rules');
function detectInputSignals(input,funnel,vision){const context=JSON.stringify({...input.context,...input.onboarding}).toLowerCase();const drop=funnel.largestDrop?.rate||0;const hasActivation=!!input.onboarding?.activation;const hasGoal=!!input.onboarding?.goal;const hasVision=vision.some(x=>x.status==='reviewed'&&Array.isArray(x.facts)&&x.facts.length);const segmentData=!!input.funnel?.segments||!!input.users?.segments;const technical=/error|failed|timeout|bug|technical/.test(context);const qualification=/qualif|screen|verification|compliance|security/.test(context);const delayed=!!input.context?.delayedActivation||/later|delayed|eventual|days? after/.test(context);return{drop,hasActivation,hasGoal,hasVision,segmentData,technical,qualification,delayed};}
function runDiagnostic(input={}){const validation=validateAnalysisInput(input),funnel=analyzeFunnel(input.funnel?.steps||[]),vision=input.screenshotAnalysis||[],sig=detectInputSignals(input,funnel,vision),hasFunnel=Array.isArray(input.funnel?.steps)&&input.funnel.steps.length>1,hypotheses=buildHypotheses({funnelAnalysis:funnel,onboarding:input.onboarding||{},screenshots:input.screenshots||[],screenshotAnalysis:vision});
 let status='insufficient_evidence';
 if(!validation.valid)status='data_quality_issue';
 else if(input.funnel?.measurementWindow&&input.funnel?.previousMeasurementWindow&&input.funnel.measurementWindow!==input.funnel.previousMeasurementWindow)status='measurement_window_issue';
 else if(!hasFunnel||!sig.hasActivation)status='insufficient_evidence';
 else if(sig.technical)status='technical_cause_possible';
 else if(sig.qualification)status='intentional_qualification_possible';
 else if(sig.delayed&&sig.drop>=.25)status='delayed_activation_possible';
 else if(sig.drop<.10)status='no_meaningful_friction_established';
 else if(!sig.segmentData)status=sig.hasVision?'segmentation_required':'potential_friction';
 else if(sig.hasVision&&sig.drop>=.20)status='meaningful_friction_signal';
 else status='normal_or_expected_behavior';
 const evidenceCompleteness=Math.min(1,(hasFunnel?.4:0)+(input.screenshots?.length?.2:0)+(input.business?.name?.1:0)+(sig.hasActivation?.15:0)+(sig.hasGoal?.1:0)+(sig.segmentData?.05:0));
 const agreement=vision.length?(sig.hasVision?.9:.45):.5;const confidence=scoreConfidence({inputValid:validation.valid,evidenceCompleteness,dataQuality:validation.errors.length?.3:.95,contextClarity:(sig.hasActivation&&sig.hasGoal)?.9:.45,agreement,contradictions:0});
 const findings=[];if(funnel.largestDrop)findings.push({title:'Observed funnel signal at '+funnel.largestDrop.step,statement:'A '+Math.round(funnel.largestDrop.rate*100)+'% sequential loss is present in the supplied measurement.',evidence_refs:['funnel']});
 const recommendations=status==='no_meaningful_friction_established'||status==='normal_or_expected_behavior'?[]:[{title:'Validate the dominant transition before redesigning it.',action:'Segment continuation and activation by user type or path, then inspect event and error evidence.',validation:'Use the same population and measurement window and compare downstream activation.',evidence_refs:['funnel']}];
 const result={version:'2.1',diagnosis_status:status,summary:status==='no_meaningful_friction_established'?'The supplied evidence does not establish meaningful onboarding friction.':'The evidence identifies a transition that warrants explanation, but causal certainty depends on the missing or supporting evidence.',confidence,validation,facts:funnel.facts||[],hypotheses,uncertainties:validation.warnings,data_quality:validation.errors,findings,recommendations,next_evidence:[...new Set(hypotheses.flatMap(h=>h.nextEvidence||[]).concat(status==='segmentation_required'?['Segment by user type and path.']:[]))],funnel_analysis:funnel,screenshot_analysis:vision,limitations:['A funnel drop is a signal, not proof of friction.','Screenshot evidence describes visible UI; it does not establish user causality.']};const check=validateDiagnosis(result);if(!check.valid)result.data_quality.push(...check.errors);return result;}
module.exports={runDiagnostic};