const {analyzeFunnel}=require("./funnel");
function diagnose(input={}){const funnel=analyzeFunnel(input.funnel||[]),facts=[],hypotheses=[],uncertainties=[],data_quality=[...funnel.warnings];
if(!input.business)uncertainties.push("Business context is missing.");if(!input.users)uncertainties.push("User definition is missing.");if(!input.activation)uncertainties.push("Activation is not clearly defined.");if((input.funnel||[]).length<2)data_quality.push("At least two sequential funnel steps are required.");
const largest=funnel.steps.filter(s=>typeof s.dropoff==="number").sort((a,b)=>b.dropoff-a.dropoff)[0];
if(largest){facts.push({type:"funnel",statement:`The largest measured sequential drop occurs after "${largest.name}" at ${(largest.dropoff*100).toFixed(1)}%.`,evidence:"funnel"});hypotheses.push({title:`"${largest.name}" is a possible friction point`,status:"needs_validation",evidence_for:["It has the largest observed sequential drop."],evidence_against:["A large drop alone does not establish friction or causality."],missing_evidence:["Segment-level continuation","Error/event data","User intent at the step"]});}
const optional=(input.optionalSteps||[]).map(x=>String(x).toLowerCase());
if(largest&&optional.includes(String(largest.name).toLowerCase()))hypotheses.push({title:`"${largest.name}" may be unnecessary for part of the audience`,status:"plausible",evidence_for:["The supplied context marks the step as optional."],evidence_against:["No segment data identifies which users need it."],missing_evidence:["Activation by path","Continuation by relevant segment"]});
if(input.recentChanges)facts.push({type:"context",statement:`Recent change: ${input.recentChanges}`,evidence:"user_input"});
let status=data_quality.length?"data_quality_issue":hypotheses.length?"potential_friction":"insufficient_evidence";
const complete=[input.business,input.users,input.activation,(input.funnel||[]).length>1,input.screenshots?.length].filter(Boolean).length*20;
const factors={evidence_completeness:complete,funnel_validity:funnel.valid?100:0,screenshot_coverage:input.screenshots?.length?100:0,context_clarity:input.activation?100:0,hypothesis_agreement:hypotheses.length?70:45};
const score=Math.round(Object.values(factors).reduce((a,b)=>a+b,0)/5);
return{diagnosis_status:status,executive_summary:hypotheses.length?"A measurable drop is present, but the supplied evidence does not establish a causal UX problem yet.":"The supplied evidence does not establish a meaningful onboarding friction point.",confidence:{score,factors},facts,hypotheses,uncertainties,data_quality,funnel_analysis:funnel,screenshot_review:(input.screenshots||[]).map(s=>({name:s.name||s.filename||"Screen",observations:["Only directly observable interface evidence is considered."],limitations:["A screenshot cannot establish user confusion or causality by itself."]})),recommendations:hypotheses.length?[{title:"Validate before redesigning",action:"Compare continuation and activation by relevant user segment, then inspect event/error evidence for the suspected step.",validation:"Use the same population and measurement window."}]:[],next_evidence:["Segment-level funnel data","Activation by onboarding path","Relevant error/event data","Screenshots from the same product version"],limitations:["A drop-off number is a signal, not proof of friction.","Screenshot observations do not establish causality."]};}
module.exports={diagnose};