const express=require("express"),crypto=require("node:crypto");
const {validateAnalysisInput,validateDiagnosis}=require("@fico/core");
const {analyses:mem,usage:memUsage}=require("./repositories/memory.repository");
const {checkAndConsumeMemory,monthKey}=require("./usage");
const {renderReport,renderPdf}=require("./report.service");
const {requireAuth,signInWithGoogle}=require("./auth");
const {getRepository}=require("./repository");
const {buildDiagnostic}=require("./diagnosis.service");
const {safeId}=require("./security");
const {addScreenshots}=require("./image");
const {begin,end}=require("./analysis-state");
const {getStorage}=require("./storage");
const router=express.Router(),repo=()=>getRepository();
const getMem=(id,o)=>{const a=mem.get(id);return a&&a.ownerId===o?a:null};
const create=async a=>repo().kind==="mongo"?repo().mongo.createAnalysis(a):(mem.set(a.id,a),a);
const get=async(id,o)=>repo().kind==="mongo"?repo().mongo.getAnalysis(id,o):getMem(id,o);
const list=async o=>repo().kind==="mongo"?repo().mongo.listAnalyses(o):[...mem.values()].filter(x=>x.ownerId===o).sort((a,b)=>b.createdAt.localeCompare(a.createdAt));
const update=async(id,o,p)=>{if(repo().kind==="mongo")return repo().mongo.updateAnalysis(id,o,p);const a=getMem(id,o);if(!a)return null;Object.assign(a,p);return a};
const usage=async u=>{const p=monthKey();if(repo().kind==="mongo"){const c=await repo().mongo.usage().findOne({userId:u,period:p});return{limit:2,used:c?.used||0,remaining:Math.max(0,2-(c?.used||0)),period:p}}const used=memUsage.get(u+"::"+p)||0;return{limit:2,used,remaining:Math.max(0,2-used),period:p}};
const consume=async u=>repo().kind==="mongo"?repo().mongo.consumeUsage(u,monthKey(),2):checkAndConsumeMemory(memUsage,u,2);
router.get("/health",(_q,r)=>r.json({ok:true,service:"fico-api"}));
router.get("/auth/google/start",(_q,r)=>{const id=process.env.GOOGLE_CLIENT_ID,redirect=process.env.GOOGLE_REDIRECT_URI;if(!id||!redirect)return r.status(503).json({error:"google_oauth_not_configured"});const u=new URL("https://accounts.google.com/o/oauth2/v2/auth");u.searchParams.set("client_id",id);u.searchParams.set("redirect_uri",redirect);u.searchParams.set("response_type","code");u.searchParams.set("scope","openid email profile");u.searchParams.set("prompt","select_account");r.redirect(u.toString())});
router.get("/auth/google/callback",async(q,r,n)=>{try{const o=await signInWithGoogle(q.query.code);const url=process.env.WEB_AUTH_SUCCESS_URL||((process.env.WEB_ORIGIN||"").split(",")[0]||"http://localhost:3000")+"/auth/callback";r.redirect(url+"?token="+encodeURIComponent(o.token))}catch(e){n(e)}});
router.use(requireAuth);
router.get("/auth/me",async(q,r)=>{const rp=repo();r.json(rp.kind==="mongo"?await rp.mongo.users().findOne({id:q.userId},{projection:{_id:0}}):(rp.memory.users.get(q.userId)||{id:q.userId}))});
router.post("/auth/logout",(_q,r)=>r.status(204).end());
router.post("/analyses",async(q,r,n)=>{try{const input=q.body||{},v=validateAnalysisInput(input);if(!v.valid)return r.status(422).json({error:"invalid_analysis_input",details:v.errors});const item={id:crypto.randomUUID(),status:"draft",input,createdAt:new Date().toISOString(),ownerId:q.userId};await create(item);r.status(201).json(item)}catch(e){n(e)}});
router.post("/analyses/:id/screenshots",async(q,r,n)=>{try{const id=safeId(q.params.id);if(!id)return r.status(400).json({error:"invalid_analysis_id"});const a=await get(id,q.userId);if(!a)return r.status(404).json({error:"analysis_not_found"});const screenshots=await addScreenshots(q,a);r.status(201).json(await update(id,q.userId,{input:{...a.input,screenshots}}))}catch(e){n(e)}});
router.delete("/analyses/:id/screenshots/:fileId",async(q,r,n)=>{try{const id=safeId(q.params.id),fid=safeId(q.params.fileId);if(!id||!fid)return r.status(400).json({error:"invalid_id"});const a=await get(id,q.userId);if(!a)return r.status(404).json({error:"analysis_not_found"});const target=(a.input.screenshots||[]).find(x=>x.id===fid);if(!target)return r.status(404).json({error:"screenshot_not_found"});await getStorage().delete(target.key);const screenshots=(a.input.screenshots||[]).filter(x=>x.id!==fid);r.json(await update(id,q.userId,{input:{...a.input,screenshots}}))}catch(e){n(e)}});
router.get("/analyses",async(q,r,n)=>{try{r.json(await list(q.userId))}catch(e){n(e)}});
router.get("/usage",async(q,r,n)=>{try{r.json(await usage(q.userId))}catch(e){n(e)}});
router.get("/analyses/:id",async(q,r,n)=>{try{const id=safeId(q.params.id);if(!id)return r.status(400).json({error:"invalid_analysis_id"});const a=await get(id,q.userId);if(!a)return r.status(404).json({error:"analysis_not_found"});r.json(a)}catch(e){n(e)}});
router.get("/analyses/:id/report.html",async(q,r,n)=>{try{const id=safeId(q.params.id),a=id&&await get(id,q.userId);if(!a)return r.status(404).json({error:"analysis_not_found"});if(!a.result)return r.status(409).json({error:"analysis_not_completed"});r.type("html").send(await renderReport(a))}catch(e){n(e)}});
router.get("/analyses/:id/pdf",async(q,r,n)=>{try{const id=safeId(q.params.id),a=id&&await get(id,q.userId);if(!a)return r.status(404).json({error:"analysis_not_found"});if(!a.result)return r.status(409).json({error:"analysis_not_completed"});r.type("application/pdf").send(await renderPdf(a))}catch(e){n(e)}});
module.exports=router;