const express=require("express"),cors=require("cors"),{initRepository}=require("./repository"),router=require("./routes"),{sendError}=require("./errors"),{requestId}=require("./security"),{rateLimit}=require("./rate-limit"),{assertConfig}=require("./config"),{log}=require("./observability");
const app=express();app.disable("x-powered-by");app.set("trust proxy",1);const origins=(process.env.WEB_ORIGIN||"").split(",").map(x=>x.trim()).filter(Boolean);
app.use(cors({origin:(o,cb)=>{if(!o||origins.includes(o))return cb(null,true);return cb(new Error("cors_origin_denied"));},credentials:true}));
app.use((req,res,next)=>{const rid=requestId();req.requestId=rid;res.setHeader("X-Request-Id",rid);res.setHeader("X-Content-Type-Options","nosniff");res.setHeader("Referrer-Policy","no-referrer");res.setHeader("X-Frame-Options","DENY");res.setHeader("Permissions-Policy","camera=(),microphone=(),geolocation=()");const started=Date.now();res.on("finish",()=>log("info","http_request",{requestId:rid,method:req.method,path:req.path,status:res.statusCode,durationMs:Date.now()-started}));next()});
app.use(express.json({limit:process.env.JSON_BODY_LIMIT||"2mb",strict:true}));
app.get("/ready",async(_req,res)=>{try{res.json(await require("./health").readiness())}catch(e){res.status(503).json({ok:false})}});
app.use("/api",rateLimit({windowMs:Number(process.env.RATE_LIMIT_WINDOW_MS||60000),max:Number(process.env.RATE_LIMIT_MAX||120)}),router);
app.use((err,_req,res,_next)=>sendError(res,err));
async function start(){assertConfig();await initRepository();const port=Number(process.env.PORT||4000);return app.listen(port,()=>log("info","server_started",{port,environment:process.env.NODE_ENV||"development"}))}
if(require.main===module)start().catch(e=>{log("error","server_start_failed",{error:e.message});process.exit(1)});module.exports=app;module.exports.start=start;