const fs=require("node:fs/promises"),path=require("node:path"),crypto=require("node:crypto");
const {S3Client,PutObjectCommand,GetObjectCommand,DeleteObjectCommand}=require("@aws-sdk/client-s3");
const {getSignedUrl}=require("@aws-sdk/s3-request-presigner");
function cleanKey(k){const s=String(k||"").replace(/^\/+/,"");if(!s||s.includes("..")||s.includes("\\\\")||s.length>512)throw Object.assign(new Error("invalid_storage_key"),{code:"invalid_storage_key",statusCode:400});return s}
class StorageAdapter{async put(){throw Object.assign(new Error("storage_not_configured"),{code:"storage_not_configured"})}async get(){throw Object.assign(new Error("storage_not_configured"),{code:"storage_not_configured"})}async delete(){throw Object.assign(new Error("storage_not_configured"),{code:"storage_not_configured"})}async url(){throw Object.assign(new Error("storage_not_configured"),{code:"storage_not_configured"})}}
class LocalStorageAdapter extends StorageAdapter{constructor(root){super();this.root=root||"/tmp/fico-storage"}async put(key,buffer,contentType){const k=cleanKey(key),file=path.join(this.root,k);await fs.mkdir(path.dirname(file),{recursive:true});await fs.writeFile(file,buffer,{flag:"wx"});return{key:k,contentType}}async get(key){return fs.readFile(path.join(this.root,cleanKey(key)))}async delete(key){await fs.rm(path.join(this.root,cleanKey(key)),{force:true})}}
class S3StorageAdapter extends StorageAdapter{constructor(){super();this.endpoint=process.env.STORAGE_ENDPOINT;this.bucket=process.env.STORAGE_BUCKET;this.accessKey=process.env.STORAGE_ACCESS_KEY;this.secretKey=process.env.STORAGE_SECRET_KEY;this.region=process.env.STORAGE_REGION||"auto";if(!this.endpoint||!this.bucket||!this.accessKey||!this.secretKey)throw Object.assign(new Error("storage_not_configured"),{code:"storage_not_configured"});this.client=new S3Client({region:this.region,endpoint:this.endpoint,forcePathStyle:process.env.STORAGE_FORCE_PATH_STYLE==="true",credentials:{accessKeyId:this.accessKey,secretAccessKey:this.secretKey}})}
async put(key,buffer,contentType){const k=cleanKey(key);await this.client.send(new PutObjectCommand({Bucket:this.bucket,Key:k,Body:buffer,ContentType:contentType,ServerSideEncryption:process.env.STORAGE_SSE||undefined}));return{key:k,contentType}}
async get(key){const out=await this.client.send(new GetObjectCommand({Bucket:this.bucket,Key:cleanKey(key)}));return Buffer.from(await out.Body.transformToByteArray())}
async delete(key){try{await this.client.send(new DeleteObjectCommand({Bucket:this.bucket,Key:cleanKey(key)}))}catch(e){if(e?.$metadata?.httpStatusCode!==404)throw Object.assign(e,{code:e.code||"storage_delete_failed"})}}
async url(key,expires=300){return getSignedUrl(this.client,new GetObjectCommand({Bucket:this.bucket,Key:cleanKey(key)}),{expiresIn:Math.min(Math.max(60,Number(expires)||300),900)})}}
function getStorage(){const mode=process.env.STORAGE_MODE||"local";if(mode==="local")return new LocalStorageAdapter(process.env.STORAGE_LOCAL_ROOT);if(mode==="s3")return new S3StorageAdapter();throw Object.assign(new Error("invalid_storage_mode"),{code:"invalid_storage_mode"})}
module.exports={StorageAdapter,LocalStorageAdapter,S3StorageAdapter,getStorage,cleanKey,randomFileId:()=>crypto.randomUUID()};